twitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('registration.auth_urls')),
]

users/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import Index, Profile, Register, Activation, ActivationResend

from django.contrib.auth.decorators import login_required

""" URL's para llevar a cabo el registro y la activacion

1. Registro -> template 'registration_form.html
    1.1 Registro completo -> template 'registration_complete.html'
2. Activacion -> template 'activate.html'
    2.1 Creacion de email
        2.1.1 Cuerpo del mensaje -> Archivo 'activation_email.txt'
        2.1.2 Asunto del mensaje -> Archivo 'activation_email_subject.txt'
    2.2 Activacion completa -> template 'activation_complete.html'

Cantidad de URL's es equivalente a la cantidad de plantillas (templates) = 4

"""
app_name="user"
urlpatterns = [
    url(r'^$', Index.as_view(), name="index"),
    url(r'^register/$', Register.as_view(), name='registration_register'),
    url(r'^register/complete$', TemplateView.as_view(template_name = 'registration/registration_complete.html'), name='registration_complete'),
    url(r'^activate/resend/$',  ActivationResend.as_view(), name='registration_resend_activation'),
    url(r'^activation/(?P<activation_key>\w+)/$', Activation.as_view(),  name='registration_activate'),
    url(r'^activation/complete$', TemplateView.as_view(template_name='registration/activation_complete.html'),  name='registration_activation_complete'),
    url(r'^profile/', login_required(Profile.as_view()), name="profile")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <script src="https://use.fontawesome.com/c1b55a37d7.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Frijole" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    {% block css %}{% endblock %}
</head>

<body>

<header>
    {% block navbar %}
    {% endblock %}
</header>

<main>
    {% block content %}
    {% endblock %}
    <hr>
</main>

<footer>
    {% block footer %}
    {% endblock %}
</footer>

<script type="application/javascript" src="{% static 'js/jquery-3.0.0.js' %}"></script>
<script type="application/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

{% block scripts %}     {% endblock %}

</body>
</html>

templates/footer.html
<div class="row">
	<div class="col-md-12 text-center">
        <p><a href="#"><i class="fa fa-github fa-1x fa-spin" aria-hidden="true"></i> Repositorio en GitHub</a></p>
        <p>Copyright &copy; <b>DGun17</b> <i class="fa fa-pencil-square-o fa-1x" aria-hidden="true"></i></p>
	</div>
</div>

templates/index.html
{% extends 'base.html' %}

{% block title %} MT - Inicio {% endblock %}


{% block css %} {% endblock %}

{% block navbar %}
        {% include 'navindex.html' %}
{% endblock %}


{% block content %}

{% load static %}

{% if request.user.is_authenticated %}
<div class="container">
	<div class="text-center">
		<h1>Tweets de todo el mundo que sigue</h1>
		<p>Aqui se podra apreciar los twiits de las personas que sigue</p>
	</div>
</div>
{% else %}
<div class="container">
	<div class="text-center">
		<h1>Mini Twiit</h1>
		<p>Una pequeña imitacion de twitter realizada en django, para probar las capacidades y entender el framework.</p>

		<p><b>Mira lo que estan compartiendo</b> <i class="fa fa-hand-o-down" aria-hidden="true"></i></p>
		<hr>
	</div>
    {% for a in object_list %}
    <div class="row">
		<div class="col-xs-0 col-md-3"></div>
		<div class="col-xs-12 col-md-6">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="media">
						<div class="media-left">
							<a href="#">
							<img class="imgprofile media-object" src="https://image.freepik.com/iconos-gratis/usuario-masculino-foto-de-perfil_318-37825.jpg" alt="chum_perfil" style="width: 64px; height:64px;">
							</a>
						</div>
						<div class="media-body">
							<h4 class="media-heading"><a href="#">{{ a.user_twit }}</a></h4>
							<p>{{ a.text }}</p>
						</div>
					</div>
				</div>
				<div class="panel-footer text-right">{{ a.date_twit }}</div>
			</div>
		</div>
		<div class="col-xs-0 col-md-3"></div>
	</div>
    {% endfor %}

    <div class="row">
		<ul class="pager">
            <li>
                <!-- Verificando si existe una pagina previa -->
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Anterior</a>
                {% endif %}
            </li>
            <li>
                <!-- Verificando si existe una siguiente pagina -->
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Siguiente <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                {% endif %}
            </li>
		</ul>
	</div>
</div>
{% endif %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

templates/navbar.html
    <nav class="navbar navbar-default">
		<div class="container-fluid">
    		<div class="navbar-header">
      			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        			<span class="sr-only">Toggle navigation</span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
      			</button>
      			<a class="logo navbar-brand" href="{% url 'user:index' %}" style="font-family: 'Frijole'; font-size: 15pt;">&lt &gt M-Twiit &lt / &gt</a>
    		</div>
    		<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">
	      		<ul class="nav navbar-nav navbar-right">


                    <li><a href="{% url 'auth_login' %}">Iniciar sesion</a></li>


	      		</ul>
    		</div>
  		</div>
	</nav>



<!--
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'user:index' %}">Inicio</a>
        </div>

        <div class="nav navbar-nav logo">
            <p class="text-center"> &lt&gt M - Twitt &lt/&gt</p>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'user:profile' %}">Perfil</a></li>
                        <li><a href="#">Modificar perfil</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'auth_password_change' %}">Cambiar contraseña</a></li>
                        <li><a href="#">Eliminar cuenta</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'auth_logout' %}">Salir</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
-->

templates/navindex.html
    <nav class="navbar navbar-default">
		<div class="container-fluid">
    		<div class="navbar-header">
      			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        			<span class="sr-only">Toggle navigation</span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
      			</button>
      			<a class="logo navbar-brand" href="{% url 'user:index' %}" style="font-family: 'Frijole'; font-size: 15pt;">&lt &gt M-Twiit &lt / &gt</a>
    		</div>
    		<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">

                {% if not request.user.is_authenticated %}
	      		<ul class="nav navbar-nav navbar-right">
					<!-- verificando URL, siempre y cuando no este en la url de registro procedo a mostrar la opcion
					en el navbar -->
					{% if not "/register" in request.get_full_path %}
	        		<li><a href="{% url 'user:registration_register' %}">Registrarse</a></li>
					{% endif %}
					<!-- verificando URL, siempre y cuando no este en la url de login procedo a mostrar la opcion
					en el navbar -->
					{% if not "/login" in request.get_full_path %}
	        		<li><a href="{% url 'auth_login' %}">Iniciar sesion</a></li>
					{% endif %}
	      		</ul>
                {% else %}
				<!-- Habilitando opciones para usuario autenticado -->
				<ul class="nav navbar-nav navbar-right">
                    {% if "/" in request.get_full_path and not "/profile" in request.get_full_path%}
                        <li><a href="{% url 'user:profile' %}">Perfil</a></li>
                    {% else %}
                        <li><a href="{% url 'user:index' %}">Inicio</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones <i class="fa fa-bars" aria-hidden="true"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Modificar perfil</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'auth_password_change' %}">Cambiar contraseña</a></li>
                                <li><a href="#">Eliminar cuenta</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'auth_logout' %}">Salir</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
                {% endif %}
    		</div>
  		</div>
	</nav>